/**
 * Every table that carries a `tenant_id` (#707 Phase 2, 20260906010000) --
 * the 73 tables given the column with a default, plus the three that take it
 * from their role by trigger, plus the three retention tables Phase 5b scoped
 * (20260906160000), plus `tenant_modules` (#900), which is the one with no
 * default on the column at all: nothing a session writes goes there.
 *
 * `audit_log` is deliberately absent: its `tenant_id` is nullable, and its
 * select policy admits rows with no tenant on purpose. It is covered by its
 * own case in the isolation suite.
 *
 * A table added later with a `tenant_id` column belongs here too. The catalog
 * side of that -- its policies carrying the tenant predicate, its foreign
 * keys being composite -- is asserted by `tenant_isolation_gaps()` regardless
 * of this list; this list is what drives the behavioural per-table checks.
 */
export const TENANT_TABLES = [
  "access_grants",
  "agenda_template_versions",
  "agenda_templates",
  "agendas",
  "annual_requirements",
  "app_settings",
  "assets",
  "board_members",
  "bylaws",
  "calendar_item_categories",
  "calendar_item_links",
  "calendar_item_programs",
  "calendar_items",
  "calendar_program_suggestion_rules",
  "conflict_of_interest_disclosures",
  "contact_messages",
  "content_brief_template_versions",
  "content_brief_templates",
  "content_opportunities",
  "content_permissions",
  "discount_codes",
  "donations",
  "event_checklist_items",
  "event_expenses",
  "event_impact_notes",
  "event_incidents",
  "event_logistics",
  "event_programs",
  "event_registrations",
  "event_revenue",
  "event_shifts",
  "event_sponsors",
  "event_staff",
  "event_volunteers",
  "events",
  "giveaway_buckets",
  "giveaway_prizes",
  "giveaway_ticket_grants",
  "giveaway_ticket_packages",
  "giveaway_ticket_sales",
  "giveaway_tier_grants",
  "giveaway_tier_rules",
  "giveaway_tiers",
  "giveaway_winners",
  "giveaways",
  "governance_meeting_action_items",
  "governance_meeting_attendees",
  "governance_meeting_decisions",
  "governance_meetings",
  "grants",
  "inventory_categories",
  "inventory_category_groups",
  "inventory_items",
  "inventory_movements",
  "monetary_donations",
  "nonprofit_status_milestones",
  "notification_deliveries",
  "partnership_opportunities",
  "people",
  "person_merges",
  "person_notification_preferences",
  "person_organizations",
  "person_role_tags",
  "policies",
  "product_variants",
  "products",
  "programs",
  "reimbursements",
  "resolutions",
  "retention_policies",
  "retention_run_tables",
  "retention_runs",
  "roles",
  "services",
  "site_content",
  "tenant_modules",
  "volunteer_applications",
  "volunteer_hours",
  "volunteer_role_types",
  "user_roles",
  "role_permissions",
  "pending_role_grants",
] as const;
